[build]
  command = "npm run build"
  publish = "build/client"

[functions]
  directory = "build/server"
  node_bundler = "esbuild"
  external_node_modules = ["react-router"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200